#!/bin/bash
set -eu
export HELM_TLS_VERIFY=true 
export PATH=$PWD/bin:$PWD/vendor/helm-tiller-manager/bin:$PATH
echo '------------------------first install cluster-----------------------'
./bin/bootstrap-infrastructure-azure up
echo '------------------------install helm into cluster-------------------'
./bin/bootstrap-system-helm up
echo '------------------------install cf-operator in k8s------------------'
./bin/bootstrap-system-cf-operator up
echo '------------------------install scf in k8s--------------------------'
./bin/bootstrap-system-scf up
echo '------------------------watch pods--------------------------'
kubectl get po -n scf -w
